### ISSUE TITLE
Problème avec le background

### ISSUE THREAD

**Issue by Venodez** [Fire-Witch/WitchOS#1]
Je ne sais pas si un problème ou non mais le background gris ne se met pas partout

**Comment by Fire-Witch** [comment]
alors tout d’abord merci pour me l'avoir fait remarquer, ce site est au tout début de son développement ducoup il y a beaucoup de bug et je ne m'attarde pas encore vraiment sur ce genre de bug, mais ducoup quel est la résolution de ton écran ? Il me semble que le problème vienne de la

**Comment by Venodez** [comment]
J'ai une résolution de 2560x1440

**Comment by Venodez** [comment]
J'ai fait des test est oui cela vient de ma résolution

**Comment by Venodez** [comment]
Une correction de ce bug est possible est remplaçant quelques lignes dan le style.css

`body{
    /* on set la margin à 0 par défault */ 
    margin: 0;
    /* on donne la largeur et la hauteur de base */
    width: 98vh;  
    height: 98vh;  
    /* on donne une image en background, on la centre et on empèche l'image de se répeter */
    background: url('../img/background.png') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}`

**Comment by Fire-Witch** [comment]
ok je vais essayer de régler ça, après pour le cover je ne suis pas sur car ce n'est pas l'effet que je recherche pour le background. Si je n'arrive pas a résoudre le problème j'utiliserai alors un cover. Merci pour ton retour et ton conseil
